In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [28]:
import numpy as np

# Create 1D array
array = np.array([[1,2,3,4,6,7,8,10]])
# array_2 = np.array([[1,2,3,4,6,7,8,10], [1,2,3,4,6,7,8,10]])
# array_3 = array + array_2

# print(array_3)

np.arange(
    start=0,
    stop=20, # Stop là điều kiện dừng khi tiếng hành tạo mảng với star < stop, step là bước nhảy khi tạo mảng start += step
    step=2
).reshape(10,1) # Số 10 phải khớp với số phần tử được tạo ra ví dụ 10 phần tử thì shape = 10

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [26]:
np.ones((3,4)) # Khởi tạo 3 hàng 4 cột với các phần tử trong mảng bằng 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(N=4) # Khởi tạo ma trận đơn vị

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
print(f'Array: {array}')
print(f'Shape: {array.shape}') # Size of dimension
print(f'Number of dimensions: {array.ndim}') # 2D 
print(f'Array size: {array.size}') # 8x8
print(f'Data type: {array.dtype}')
print(f'Device used: {array.device}')
print(f'Item size: {array.itemsize}')

Array: [[ 1  2  3  4  6  7  8 10]]
Shape: (1, 8)
Number of dimensions: 2
Array size: 8
Data type: int64
Device used: cpu
Item size: 8


In [41]:
# Vectorize array

arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([10,11,12,13,14])

print(f'Addtional: {arr_1 + arr_2}')
print(f'Substraction: {arr_1 - arr_2}')
print(f'Multiplication: {arr_1 * arr_2}')
print(f'Division: {arr_1 / arr_2}')

Addtional: [11 13 15 17 19]
Substraction: [-9 -9 -9 -9 -9]
Multiplication: [10 22 36 52 70]
Division: [0.1        0.18181818 0.25       0.30769231 0.35714286]


In [43]:
print(arr_1.shape)
print(np.sqrt(arr_1))
print(np.exp(arr_1)) # e^x e = euler constant = 2.71828183, x = value in array
print(np.sin(arr_1))
#print(np.exp(arr_1))

(5,)
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [54]:
arr_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_1[::-1])

print(arr_1[:,::-1]) # arr_1[<dòng>, <cột>]

print(arr_1[::-1,::-1]) # arr_1[<dòng>, <cột>]

arr_1[0,0]=100

arr_1



[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [59]:
data = np.array([1,2,3,4,5])

mean = np.mean(data) # Lấy trung bình các phần tử trong mảng
std_dev = np.std(data) # Độ lệch chuẩn
print(f'{mean} - {std_dev}')

normalize_data = (data - mean) / std_dev
print(normalize_data)
print(np.median(data)) # Lấy giá trị ở giữa sau khi dãy được sắp xếp tăng dần
print(np.var(data)) # Phương sai với công thức ((1 - 3)^2) + (2 - 3)^2 + (3-3)^2 + (4 - 3)^2 + (5 - 3) ^ 2) / 5
                    # 5 = n
                    # 1,2,3,4,5 = ni
                    # 3 = mean 

3.0 - 1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
2.0


In [67]:
data = np.array([1,2,3,4,5])
data[(data > 2) & (data <= 4)]

array([3, 4])